cursor #f8f8f2
cursor_text_color #f8f8f2

foreground            #f8f8f2
background            #282a36
selection_foreground  #282a36
selection_background  #ff79c6
url_color             #bd93f9

color0   #21222c
color1   #ff728d
color2   #7cf998
color3   #ffda72
color4   #a878ec
color5   #401c73
color6   #bd93f9
color7   #f6efff
color8   #9a95a1
color9   #ff9fb1
color10  #a5ffb9
color11  #ffe8a5
color12  #caa6ff
color13  #d3b5ff
color14  #e3cfff
color15  #fbf8ff
