#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr | grep " connected" | cut -d" " -f1 | while read monitor
do
    bspc monitor $monitor -d I II III IV V VI VII VIII IX X
done


bspc config border_width         4
bspc config window_gap          10

bspc config split_ratio           0.5
bspc config single_monocle        false
bspc config focus_follows_pointer true
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focused_border_color    "#BD93F9"
bspc config normal_border_color     "#282A36"
bspc config active_border_color     "#8BE9FD"
bspc config presel_feedback_color   "#50FA7B"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill $HOME/.dotfiles/common/images/wallpaper.jpg
$HOME/.dotfiles/common/scripts/picom.sh &
$HOME/.dotfiles/common/scripts/polybar.sh &

dunst &
xset r rate 200 50
